---

#ansible_python_interpreter: /usr/bin/python3


ansible_ssh_user: "vagrant"
ansible_ssh_port: "22"
ansible_connection: "ssh"

become: True
become_user: root
become_method: sudo


dns_domain: "cluster.local"

weave_password: "Sahph2eechua7aih5aiR4euvooluom"
weavescope_enable: false 
dns1: "8.8.8.8"
dns2: "8.8.8.4"
mesos_clustername: "mesos"
mesos_password: "woowuHohboozahb6owee4ahyah3ief"
marathon_basic_auth: "marathon:Aipo8weeW1uchai5see9eedei0ziez"
quorum: "1"

zookeeper_admin_secret: "aoSeizapho3tuze2ecoLive5zie4ey"
zookeeper_client_secret: "aoSeizapho3tuze2ecoLive5zie4ey"

libprocess_enable_ssl: "true"

mesos_docker_config_enable: false
mesos_enable_systemd: "false"
mesos_containerizer_list: 
  - docker

druid_segmentcache_locations: "/data/segment-cache"  
druid_indexer_task_baseTaskDir: "/data/indexer-task"  
druid_indexer_task_hadoopWorkingPath: "/data/hadoop-tmp"
druid_lookup_snapshotWorkingDir: "/data/lookup-config"  
druid_jvm_io_tmpdir: "/data/lookup-ram"
druid_jvm_io_tmpdir_tmpfs: true
druid_jvm_io_tmpdir_tmpfs_size: "10M"
druid_log_dir: "/data/logs"  
druid_middlemanager_jvm_io_tmpdir: "/data/middlemanager-tmp"
  
    


